#!/usr/bin/env python
from anime_list.web import app
# from anime_list.anime import get_animes
#
# animes, faileds = get_animes('/media/nekhd/Anime')
# for failed in faileds:
#     print(failed)


if __name__ == '__main__':
    app.config['TEMPLATES_AUTO_RELOAD'] = True
    app.config['DEBUG'] = True
    app.debug = True
    app.run()
